---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: test/encrypted_data_bag_secret
  data_bags_path: test/data_bags

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: centos-7.0
  - name: debian-7.6

suites:
  - name: default
    run_list:
      - recipe[golang]
      - recipe[serf]
      - recipe[shovey-jobs::default]
    attributes: { schob: { pem_server: "localhost" } }
